env: flex
runtime: custom
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
health_check:
  enable_health_check: true
  check_interval_sec: 8
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
